[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]

fixable = ["ALL"]
unfixable = []

exclude = ["tests/*"]

[tool.ruff.format]
quote-style = "double"

[tool.ruff.pydocstyle]
convention = "google"
